module Rley
  module GFG
    # Represents an edge in a grammar flow graph
    # without change of the position in the input stream.
    # Responsibilities:
    # - To know the successor vertex
    class EpsilonEdge < Edge
      # The destination vertex of the edge.
      attr_reader successor: Vertex
    end
  end
end
