AllCops:
  Exclude:
    - 'exp/**/*'

Gemspec/DateAssignment:
  Enabled: true

Gemspec/RequireMFA: # new in 1.23
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true

Layout/HeredocIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: false

Lint/EmptyInPattern:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true
  
Lint/RefinementImportMethods: # new in 1.27
  Enabled: true  

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessRuby2Keywords: # new in 1.23
  Enabled: true

Lint/Void:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Max: 350

Metrics/BlockNesting:
  Enabled: true
  Max: 5

Metrics/ClassLength:
  Enabled: true
  Max: 450

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Max: 90

Metrics/MethodLength:
  Enabled: true
  Max: 60

Metrics/ModuleLength:
  Enabled: true
  Max: 500

Metrics/PerceivedComplexity:
  Enabled: false

Naming/BlockForwarding: # new in 1.24
  Enabled: true

Naming/ConstantName:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/BlockParameterName:
  Enabled: true

Naming/InclusiveLanguage:
  Enabled: true

Naming/MethodParameterName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Security/IoMethods:
  Enabled: true

Style/Alias:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FileRead: # new in 1.24
  Enabled: true

Style/FileWrite: # new in 1.24
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/InPatternThen:
  Enabled: true

Style/InverseMethods:
  Enabled: false

Style/MapToHash: # new in 1.24
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true
  
Style/NestedFileDirname: # new in 1.26
  Enabled: true

Style/Next:
  Enabled: false

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/OpenStructUse: # new in 1.23
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RedundantArgument:
  Enabled: true
  
Style/RedundantInitialize: # new in 1.27
  Enabled: true  

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SelectByRegexp:
  Enabled: true

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/TernaryParentheses:
  Enabled: false

Style/UnlessElse:
  Enabled: false

# Rubocop complains when it doesn't find an explicit setting for the following cops:
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true