module Rley
  # Factory method.
  # A grammar builder constructs a Rley grammar piece by piece
  # from DSL instructions in a provided code block.
  # @param aBlock [Proc] a code block
  # @return [Rley::RGN::GrammarBuilder] An object that builds a grammar.
  def self.grammar_builder: () { (?) -> untyped } -> RGN::GrammarBuilder
end
