module Rley
  module Base
    # Mix-in module. Builds the dotted items for a given grammar
    module GrmItemsBuilder
      # Build an array of dotted items from the productions of passed grammar.
      # @param aGrammar [Syntax::Grammar]
      # @return [Array<DottedItem>]
      def build_dotted_items: (Syntax::Grammar aGrammar) -> Array[DottedItem]
    end
  end
end
