inherit_from:
  - ../.rubocop.yml 

Metrics/AbcSize:
  Max: 60
  
Metrics/BlockLength:
  # Long blocks are frequent in spec files...
  Max: 200
  CountComments: false
  
Style/AccessorGrouping:
  Enabled: false  
  
Style/ClassVars:
  Enabled: false
  
Style/PerlBackrefs:
  Enabled: false
