require 'rake'

# Utility method
# Display summary diagnosis message.
def diagnosis(outcomes)
  failure_count = outcomes.count { |result| ! result }
  if failure_count > 0
    puts "#{outcomes.size} examples, of which #{failure_count} failed!"
  else
    puts "All #{outcomes.size} examples passed."
  end
end

# Utility method.
# Run all sample Ruby scripts in given sub-folders.
# Give summary diagnosis at the end of execution
def run_samples_from(aPath)
  filenames = Dir[aPath]
  results = filenames.map do |fname| 
    result = system("ruby #{fname}")
  end
  
  diagnosis(results)
end

namespace :sample do
  desc 'Run sample grammar creation'
  task :grammars do
    run_samples_from('grammars/*.rb')
  end

  desc 'Run sample recognizers'
  task :recognizers do
    run_samples_from('recognizers/*.rb')
  end

  desc 'Run sample parsers'
  task :parsers do
    run_samples_from('parsers/*.rb')
  end
  
  desc 'Run all samples'
  task all: [:grammars, :recognizers, :parsers]
end # namespace

 

# Default rake task
task default: :"sample:all"

# End of file